# Utiliser l'image officielle de WordPress avec PHP-FPM
FROM wordpress:php8.0-fpm

# Exposer le port utilisé par PHP-FPM
EXPOSE 9000

# Installer les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd

# Copier les fichiers de configuration de WordPress
COPY . /var/www/html

# Changer les droits d'accès
RUN chown -R www-data:www-data /var/www/html

# Démarrer PHP-FPM
CMD ["php-fpm"]
